# Generated by Django 4.2.1 on 2023-06-16 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=120)),
                ('school', models.CharField(max_length=200)),
                ('deadline', models.DateField(null=True)),
                ('more_info', models.TextField()),
                ('description', models.TextField(blank=True, max_length=275, null=True)),
                ('link_web', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=120)),
                ('slug', models.SlugField(default='0ktvke43lkcwmw6g3nljrg9x6jl48u4d', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='images\\profile_pics\\Default.png', upload_to='images\\profile_pics')),
                ('bio', models.TextField(blank=True, default='This user is lazy and has nothing to say.', max_length=124, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
