# Generated by Django 4.2 on 2023-05-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.CharField(choices=[('ASIA', 'Asia'), ('AFRIC', 'Africa'), ('NA', 'North America'), ('SA', 'South America'), ('ANTIC', 'Antacitica'), ('EURO', 'Europe'), ('AUS', 'Australia')], max_length=5),
        ),
    ]
