# Generated by Django 4.2 on 2023-05-01 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_country_continent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.country'),
        ),
    ]
