# Generated by Django 4.2.1 on 2023-06-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_scholarship_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='country',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='deadline',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='level',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='link_web',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='school',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='slug',
            field=models.SlugField(default='function-random_slug-at-0x000001cc50db2dd0', unique=True),
        ),
    ]
