# Generated by Django 4.2 on 2023-05-01 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_scholarship_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='continent',
        ),
    ]
