# Generated by Django 4.2 on 2023-05-21 16:25

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_profile_phone_profile_profile_profile_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='src/template/user/profile_pictures', verbose_name=django.contrib.auth.models.User),
        ),
    ]
