# Generated by Django 4.2.1 on 2023-06-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_comment_user_alter_reply_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='slug',
            field=models.SlugField(default='9wwollwv79wblbo2bwzzbtvtfom0gcc7', unique=True),
        ),
    ]
