# Generated by Django 4.2 on 2023-05-21 16:35

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_profile_major_alter_profile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Project\\CAPPLY-\\CAPPLY--1\\src\\template\\user\\profile_pictures', verbose_name=django.contrib.auth.models.User),
        ),
    ]
