# Generated by Django 4.2 on 2023-05-22 14:38

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_alter_profile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='src\\static\\images\\profile_pic', verbose_name=django.contrib.auth.models.User),
        ),
    ]
