# Generated by Django 4.2.1 on 2023-06-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_alter_scholarship_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='slug',
            field=models.SlugField(default='wtjxidedlfwygmqz5grryclbqgqz2ail', unique=True),
        ),
    ]
