# Generated by Django 4.2.1 on 2023-06-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_alter_scholarship_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='slug',
            field=models.SlugField(default='dmgoot61vyqwtxny0vtia11vsn07wmr6', unique=True),
        ),
    ]
