# Generated by Django 4.2 on 2023-05-23 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_remove_profile_profile_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
