# Generated by Django 4.2 on 2023-05-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_remove_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='static\\images\\profile_pics\\Default.png', upload_to='static\\images\\profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='This user is lazy and has nothing to say.', max_length=124, null=True),
        ),
    ]
