# Generated by Django 4.2 on 2023-05-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0013_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='description',
            field=models.TextField(blank=True, max_length=275, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='major',
            field=models.CharField(blank=True, choices=[('computer science', 'COMPUTER SCIENCE'), ('finance', 'FINANCE'), ('business administration', 'BUSINESS ADMINISTRATION')], default='N/A', max_length=40, null=True),
        ),
    ]
